### PR TITLE
Add a test suite and a first test

### LINKED ISSUE #62: Is there a test suit? Should there be one?
There is a `test` folder but no testing code to be found anywhere. Is there any plan to add a test suit? And if yes which framework is to be used? I would like to help with that in order to make further changes easier to check for bugs.

### PR DESCRIPTION
**Pull request by lucc**
If the infrastructure is in place we can start to add tests for different things.

The first things that come to mind (and that might already be somewhat complicatet) are
- parsing config files
- parsing example vcard files
- exporting and reimporting contacts

If we write tests that interact with the vcard store and the config file we have to take care to _never_ use the config file and vcards of the user.

Fixes #62.

### CODE REVIEW

**Comment by lucc** [comment]
Should I add more tests here or wait for this to be merged and open new PRs for new tests?

**Comment by scheibler** [comment]
Definitely necessary. Thanks.

The command line test case looks like a good start. But I've a problem with the
test_khard_runner_script method. My khard python environment is located within a virtual environment
while the khard-runner.py interpreter points to the default python location. Therefore the
corresponding test fails.

The only workaround I found so far is to change the khard-runner.py interpreter to my custom python
installation. But I would have to undo that change before every commit. Can you eventually think of
a better solution for that?

**Comment by lucc** [comment]
I learned some new tricks when we started to write unittests for alot so I updated the mocking part of the tests.

I removed the khard-runner test for now. We can resurrect it from the git history if we want. I will try to spend as little time as possible on testing the cli as I think it is the least important part to test (also something I learned from the alot tests).

Would you be interested in running the tests on travis?

**Comment by strk** [comment]
May be a good idea to also add a .travis.yml in this PR, and enable it for your fork , @lucc ?

**Comment by lucc** [comment]
@strk it is [here](https://travis-ci.org/lucc/khard).

**Comment by strk** [comment]
Great work !

**Comment by josephholsten** [comment]
@scheibler what's remaining to merge this?

**Comment by andrey-utkin** [comment]
Gentoo package app-misc/khard maintainers appreciate this work on actual runnable tests. Waiting for resolution.

**Comment by lucc** [comment]
@scheibler I would like to merge this rather sooner than later and also would ask you to go to travis and activate tests for this repository. You could configure it to run tests on every PR.

**Comment by lucc** [comment]
By the way these test also pass when I merge them with current master locally :)

**Comment by josephholsten** [comment]
I’ve requested pimutils give us a place to maintain a fork of khard: https://github.com/pimutils/meta/issues/10

This is pretty near the top of list of things I hope we can resolve once we have a new home!

**Comment by scheibler** [comment]
@lucc: travis should be activated for the khard repo. Feel free to merge and test.

@josephholsten: Please see my update on #144

**Comment by lucc** [comment]
Thank you @scheibler !

**Pull request merged**
