### PR TITLE
Fixes a problem with the _search_all function in address_book.py

### PR DESCRIPTION
**Pull request by scheibler**

### CODE REVIEW

**Comment by lucc** [comment]
I can not reproduce this. For me `khard ls eluc` returns nothing. But the code looks good and doesn't seem to break anything. (Dumb question did you check that Ricarda doesn't have the string "eric" anywhere else in the vcard?)

**Comment by scheibler** [comment]
@lucc:
> did you check that Ricarda doesn't have the string "eric" anywhere else in the vcard?)

That's the point. "Ricarda" itself doesn't contain the search query "eric". But ...

First in the _search_all function, the search query regexp is matched against the output of
print_vcard() (not only the name). So we match:

"Name: Ricarda\n[...]" contains "eric" == False

That's correct.

Then look at the phone number hack in the next line where the output of print_vcard() is stripped of
all non-letters and -numbers to find phone numbers too. So now we match:

"NameRicarda\n[...]" contains "eric" == True

And that's not right.

Problem: "Nam<eRic>arda\n[...]" and the case insensitive regexp

Of course that's a really rare scenario but nevertheless not impossible. Otherwise I wouldn't
encountered it :-).

**Comment by lucc** [comment]
PS: travis will fail until we merge in the stuff from develop with v0.13 so from my point of view this can be merged (if you want to cut down on releases you could merge this and #159 and release 0.12.2 only after both are merged).

**Comment by scheibler** [comment]
Merged into master and develop

**Pull request closed without merging**
