### PR TITLE
Automate deploy of PyPI releases with travis

### PR DESCRIPTION
**Pull request by lucc**
<s>**This is currently Work In Progress!**</s>

The idea was born from #215. I plan to test this on https://github.com/lucc/khard with test.pypi.org and report back.

### CODE REVIEW

**Comment by lucc** [comment]
I created https://test.pypi.org/project/khard-test-lucc/ to test this. Under https://test.pypi.org/manage/account/token/ one can create an api token for just one project that can then be used to upload releases.

With the travis ruby gem the token from pypi can be encrypted and added in the password field.

**Comment by lucc** [comment]
It worked:

https://travis-ci.org/lucc/khard/jobs/608152594

https://test.pypi.org/project/khard-test-lucc/3.0.0/

@scheibler could you please create an api key for the khard project on pypi.org under https://pypi.org/manage/account/token/
And next encrypt it with your travis account (it will not work when you send me the token and I encrypt it with my travis account as the builds on your account need to be able to decrypt it). You will need [the travis gem](https://github.com/travis-ci/travis.rb) and then run `travis encrypt pypi-TOKEN-XYZ`.  The result can replace the encrypted token I put there for test.pypi.org.

**Comment by lucc** [comment]
Note to self and @scheibler: I just found [an action to push to pypi on a github release](https://github.com/actions/starter-workflows/blob/master/ci/python-publish.yml). This would be an alternative to having travis push the release.

See [the difference between releases and tags](https://stackoverflow.com/questions/18506508/whats-the-difference-between-tag-and-release). We currently only have tags in this repository.  Travis would do the release on a tag, github would do it on a release.

Pros and Cons:
- travis runs the test suite
- travis needs admin rights to the from @scheibler which @lucc does not have (the current rights on github seem to be enough)
- tags are our current/past workflow, releases are not

**Comment by lucc** [comment]
@scheibler If you can work on this issue I could also do some work and make releases during the corona quarantine.

We have lockdown and I thought I could use the time :)

**Comment by lucc** [comment]
@scheibler has mentioned concerns about giving travis access to the pypi account.  So until further notice this will not happen and all releases will be uploaded manually.

Notes to self for the release process:
```sh
git flow release start vXXX
git log vLAST.. 
$EDITOR CHANGES
git cm 'Update changelog for version vXXX' CHANGES
git tag vXXX.rc1
python3 setup.py sdist bdist_wheel
twine check dist/*
twine upload -r khardtest dist/*
git push --set-upstream origin release/vXXX
hub ci-status release/vXXX
git flow release finish
git push origin master develop vXXX
python3 setup.py sdist bdist_wheel
twine check dist/*
twine upload -r khard dist/*
```

**Comment by tannewt** [comment]
pypi now has api tokens so you don't need to give CIs full username/password: https://pypi.org/help/#apitoken

**Comment by Tonus1** [comment]
Any news on this ? I might have missed something...

**Comment by lucc** [comment]
Eric and I have discussed this and the decision was that it will not happen currently. I will publish releases on pypi manually.

**Pull request closed without merging**
